#!/usr/bin/python3
#	pibeatsaber - Beat Saber historian application that tracks players
#	Copyright (C) 2019-2019 Johannes Bauer
#
#	This file is part of pibeatsaber.
#
#	pibeatsaber is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	pibeatsaber is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import sys
import json
import gzip
from FriendlyArgumentParser import FriendlyArgumentParser

parser = FriendlyArgumentParser(description = "Beat Saber Historian, fixes up JSON files.")
parser.add_argument("-p", "--player", metavar = "playername", type = str, help = "When no player was set, change the player name to this.")
parser.add_argument("-c", "--config-file", metavar = "filename", type = str, default = "configuration.json", help = "Specifies JSON config file to use. Defaults to %(default)s.")
parser.add_argument("-v", "--verbose", action = "count", default = 0, help = "Increases verbosity. Can be specified multiple times to increase.")
parser.add_argument("jsonfile", metavar = "jsonfile", nargs = "+", help = "JSON file(s) to fix up.")
args = parser.parse_args(sys.argv[1:])

for filename in args.jsonfile:
	if filename.endswith(".gz"):
		with gzip.open(filename) as f:
			history = json.load(f)
	else:
		with open(filename) as f:
			history = json.load(f)

	if args.verbose >= 1:
		print(filename)

	if (args.player is not None):
		if history["meta"]["player"] is None:
			 history["meta"]["player"] = args.player
			 print("%s: Player set to \"%s\"" % (filename, args.player))

	if filename.endswith(".gz"):
		with gzip.open(filename, "wt") as f:
			json.dump(history, f)
	else:
		with open(filename, "w") as f:
			json.dump(history, f)
